# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages:
  roxygen2 

addons:
  apt:
    packages:
      - libgdal-dev # for installing rgdal 
      - libopenmpi-dev # for Rmpi 
      - openmpi-bin
      - libproj-dev
      - libgeos-dev
